#include <omp.h>
#include <stdio.h>
#include <stdlib.h>
#include "ompvv.h"
int test_function() {
int errors = 1;
#pragma omp target map(from: errors)
{
errors = 0;
}
return errors;
}
int main() {
OMPVV_TEST_OFFLOADING; 
OMPVV_INFOMSG("THIS IS IS AN EXAMPLE OF AN INFOMSG");
OMPVV_INFOMSG("THIS IS IS AN EXAMPLE OF AN INFOMSG WITH PARAMETERS (%d, %s, %f)", 3, "ompvv", 3.3);
OMPVV_INFOMSG_IF(1==1, "THIS IS IS AN EXAMPLE OF AN INFOMSG_IF 1==1");
OMPVV_INFOMSG_IF(1==0, "THIS IS IS AN EXAMPLE OF AN INFOMSG_IF 1==0 (THIS SHOULD NOT BE DISPLAYED)");
OMPVV_WARNING("THIS IS IS AN EXAMPLE OF A WARNING");
OMPVV_WARNING("THIS IS IS AN EXAMPLE OF A WARNING WITH PARAMETERS (%d, %s, %f)", 3, "ompvv", 3.3);
OMPVV_WARNING_IF(1==1, "THIS IS IS AN EXAMPLE OF AN INFOMSG_IF 1==1");
OMPVV_WARNING_IF(1==0, "THIS IS IS AN EXAMPLE OF AN INFOMSG_IF 1==0 (THIS SHOULD NOT BE DISPLAYED)");
OMPVV_ERROR("THIS IS IS AN EXAMPLE OF AN ERROR");
OMPVV_ERROR("THIS IS IS AN EXAMPLE OF AN ERROR WITH PARAMETERS (%d, %s, %f)", 3, "ompvv", 3.3);
OMPVV_ERROR_IF(1==1, "THIS IS IS AN EXAMPLE OF AN ERROR_IF 1==1");
OMPVV_ERROR_IF(1==0, "THIS IS IS AN EXAMPLE OF AN ERROR_IF 1==0 (THIS SHOULD NOT BE DISPLAYED)");
int errors = 0;
OMPVV_TEST_AND_SET(errors, 1!=0); 
OMPVV_TEST_AND_SET_VERBOSE(errors, 1!=0); 
OMPVV_REPORT(errors); 
errors = 0;
OMPVV_TEST_AND_SET(errors, 1==0); 
OMPVV_TEST_AND_SET_VERBOSE(errors, 1==0); 
errors = test_function();
OMPVV_REPORT(errors);  
OMPVV_RETURN(errors); 
}
