
#pragma once



#include "includes/define.h"
#include "containers/variable.h"

namespace Kratos
{
KRATOS_DEFINE_APPLICATION_VARIABLE( MAPPING_APPLICATION, int, INTERFACE_EQUATION_ID ) 
KRATOS_DEFINE_APPLICATION_VARIABLE( MAPPING_APPLICATION, int, PAIRING_STATUS )
KRATOS_DEFINE_3D_APPLICATION_VARIABLE_WITH_COMPONENTS( MAPPING_APPLICATION, CURRENT_COORDINATES )
KRATOS_DEFINE_APPLICATION_VARIABLE( MAPPING_APPLICATION, bool, IS_PROJECTED_LOCAL_SYSTEM)
KRATOS_DEFINE_APPLICATION_VARIABLE(MAPPING_APPLICATION, bool, IS_DUAL_MORTAR)
}
