
#ifndef BOOST_ASIO_DETAIL_CONCURRENCY_HINT_HPP
#define BOOST_ASIO_DETAIL_CONCURRENCY_HINT_HPP

#if defined(_MSC_VER) && (_MSC_VER >= 1200)
# pragma once
#endif 

#include <boost/asio/detail/config.hpp>
#include <boost/asio/detail/noncopyable.hpp>

#define BOOST_ASIO_CONCURRENCY_HINT_ID 0xA5100000u
#define BOOST_ASIO_CONCURRENCY_HINT_ID_MASK 0xFFFF0000u

#define BOOST_ASIO_CONCURRENCY_HINT_LOCKING_SCHEDULER 0x1u

#define BOOST_ASIO_CONCURRENCY_HINT_LOCKING_REACTOR_REGISTRATION 0x2u

#define BOOST_ASIO_CONCURRENCY_HINT_LOCKING_REACTOR_IO 0x4u

#define BOOST_ASIO_CONCURRENCY_HINT_IS_SPECIAL(hint) \
((static_cast<unsigned>(hint) \
& BOOST_ASIO_CONCURRENCY_HINT_ID_MASK) \
== BOOST_ASIO_CONCURRENCY_HINT_ID)

#define BOOST_ASIO_CONCURRENCY_HINT_IS_LOCKING(facility, hint) \
(((static_cast<unsigned>(hint) \
& (BOOST_ASIO_CONCURRENCY_HINT_ID_MASK \
| BOOST_ASIO_CONCURRENCY_HINT_LOCKING_ ## facility)) \
^ BOOST_ASIO_CONCURRENCY_HINT_ID) != 0)

#define BOOST_ASIO_CONCURRENCY_HINT_UNSAFE \
static_cast<int>(BOOST_ASIO_CONCURRENCY_HINT_ID)

#define BOOST_ASIO_CONCURRENCY_HINT_UNSAFE_IO \
static_cast<int>(BOOST_ASIO_CONCURRENCY_HINT_ID \
| BOOST_ASIO_CONCURRENCY_HINT_LOCKING_SCHEDULER \
| BOOST_ASIO_CONCURRENCY_HINT_LOCKING_REACTOR_REGISTRATION)

#define BOOST_ASIO_CONCURRENCY_HINT_SAFE \
static_cast<int>(BOOST_ASIO_CONCURRENCY_HINT_ID \
| BOOST_ASIO_CONCURRENCY_HINT_LOCKING_SCHEDULER \
| BOOST_ASIO_CONCURRENCY_HINT_LOCKING_REACTOR_REGISTRATION \
| BOOST_ASIO_CONCURRENCY_HINT_LOCKING_REACTOR_IO)

#if !defined(BOOST_ASIO_CONCURRENCY_HINT_DEFAULT)
# define BOOST_ASIO_CONCURRENCY_HINT_DEFAULT -1
#endif 

#if !defined(BOOST_ASIO_CONCURRENCY_HINT_1)
# define BOOST_ASIO_CONCURRENCY_HINT_1 1
#endif 

#endif 
